theme: jekyll-theme-minimal
title: Junior for firedev
description: Quick guides and explanations for junior developers
domain: junior.firedev.se       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://junior.firedev.se  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /gh-pages/      # place folder name if the site is served in a subfolder